config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      put :change
    end  
  end
  
  devise_for :views
  devise_for :users
  resources :posts
  get 'home/index'
  get 'teste' => 'home#teste'
  get 'about' => 'home#about'

  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
    belongs_to :user
    
    auto_html_for :content do
        
        html_escape
        image 
        youtube(:width => "100%", :height => 250, :autoplay => false)
        link :target => "_blank", :rel => "nofollow"
        simple_format
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatables
  has_many :tasks, dependent: :destroy
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def teste
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :autor, :body, :url, :tag)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change]
  before_action :authenticate_user!

  # GET /tasks
  # GET /tasks.json
  def index
    @to_do = current_user.tasks.where(state: 'to_do')
    @doing = current_user.tasks.where(state: 'doing')
    @done = current_user.tasks.where(state: 'done')
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def change
    @task.update_attributes(state: params[:state])
    respond_to do |format|
    format.html{redirect_to tasks_path, notice: "Tasks status successfully changed"}  
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_text.html.erb
<p>Frequentemente referenciado como Rails ou RoR, o Ruby on Rails <br />
é um projeto de código aberto escrito na linguagem de programação <br />
Ruby. As aplicações criadas utilizando o framework Rails são <br />
desenvolvidas com base no padrão de arquitetura MVC (Model-View-Controller).</p>

app/views/home/about.html.erb
<div class="panel"></div>
    
    <div class="panel panel-heading">
        <h1>About Framework</h1>
    </div>

    <div class="panel panel-body">
        <p>Ruby é uma linguagem de programação interpretada multiparadigma, <br /> 
        de tipagem dinâmica e forte, com gerenciamento de memória automático, <br /> 
        originalmente planejada e desenvolvida no Japão em 1995, por Yukihiro "Matz" <br /> 
        Matsumoto, para ser usada como linguagem de script.</p>
    </div>
    
    <div class="panel-footer text-center">
        <%= link_to '<i class="fa fa-long-arrow-left fa-3x" aria-hidden="true"></i>'.html_safe, home_index_path%>
    </div>
    
</div>

app/views/home/index.html.erb
<div class="jumbotron">
    <h2>Tarefas</h2>
    <p>Aplicativo de tarefas desenvolvido com framework Ruby on Rails</p>
    
    <% if current_user %>
        <%= link_to '<i class="fa fa-list" aria-hidden="true"></i> Show tasks'.html_safe, tasks_path, class: "btn btn-primary btn-lg" %>
    <% else %>
        <%= link_to '<i class="fa fa-user-plus" aria-hidden="true"></i> Sign up'.html_safe, new_user_registration_path, class:"btn btn-primary btn-lg"%>
    <% end %>
</div>

app/views/home/teste.html.erb
<div class="row">

    <div class="col-md-4">
        <h1 class="text-center">To do</h1>
        <div class="panel panel-info">
            <div class="panel-heading">My todo</div>
            <div class="panel-body">Need to update this</div>
            <div class="panel-footer text-center">Change state</div>
        </div>
    </div>
    
    <div class="col-md-4">
        <h1 class="text-center">Doing</h1>
        <div class="panel panel-info">
            <div class="panel-heading">My todo</div>
            <div class="panel-body">Need to update this</div>
            <div class="panel-footer text-center">Change state</div>
        </div>
    </div>
    
    <div class="col-md-4">
        <h1 class="text-center">Done</h1>
        <div class="panel panel-info">
            <div class="panel-heading">My todo</div>
            <div class="panel-body">Need to update this</div>
            <div class="panel-footer text-center">Change state</div>
        </div>
    </div>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <li><%=link_to "<i class='fa fa-circle-o-notch'></i> SENAI ".html_safe, root_path, class:"navbar-brand" %></li>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
        <ul class="nav navbar-nav">
          <li><%=link_to " <i class='fa fa-plus-square' aria-hidden='true'></i> New Task".html_safe, new_task_path, class:"navbar-brand" %></li>
        </ul>
      <% end %>
        
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%=link_to '<i class="fa fa-pencil" aria-hidden="true"></i> Edit profile'.html_safe, edit_user_registration_path %></li>
          <li><%=link_to '<i class="fa fa-sign-out" aria-hidden="true"></i> Sign out'.html_safe, destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%=link_to '<i class="fa fa-comment-o" aria-hidden="true"></i> About'.html_safe, about_path %></li>
          <li><%=link_to '<i class="fa fa-sign-in" aria-hidden="true"></i> Sign in'.html_safe, new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/header' %>
  
<div class="container"> <%= yield %> </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  
  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  
  <div class="field">
    <%= f.label :Descricao %><br>
    <%= f.text_area :body %>
  </div>
  
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Autor</th>
      <th>Body</th>
      <th>Url</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.titulo %></td>
        <td><%= post.autor %></td>
        <td><%= post.body %></td>
        <td><%= post.url %></td>
        <td><%= post.tag %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Deseja mesmo excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>Nova entrada</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @post.titulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @post.autor %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @post.tag %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task, html: {class:'form-signin'} ) do |f| %>
  <%= f.error_notification %>

  <%= f.input :content, required: true, label: false, autofocus: true, placeholder: "Content", input_html: {class: 'form-control'} %>
  
  <%= f.button :submit, class: "btn btn-primary btn-lg btn-block" %>
  
<% end %>

app/views/tasks/_task.html.erb
    <div class="panel panel-info">
        
        <div class="panel-heading">Created <%= time_ago_in_words(task.created_at) %> </div>
        
        <div class="panel-body">
        
            <ul class="list-group">
                
            <li class="list-group-item active"><%= task.content %></li>
            <li class="list-group-item active"><%= raw(task.content_html) %></li>
            
            <li class="list-group-item"><i class="fa fa-info-circle" aria-hidden="true"></i> <%= link_to 'Show', task %></li>
            <li class="list-group-item"><i class="fa fa-pencil-square" aria-hidden="true"></i> <%= link_to 'Edit', edit_task_path(task) %></li>
            <li class="list-group-item"><i class="fa fa-trash-o" aria-hidden="true"></i> <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        
            </ul>
        
        </div>
        
        <div class="panel-footer text-center">
            <ul class="list-group">
            <% if task.state == "doing" %>
                <%= link_to '<i class="fa fa-arrow-circle-left fa-2x" aria-hidden="true"></i>'.html_safe, change_task_path(task, state: "to_do"), method: :put %>
                <%= link_to '<i class="fa fa-arrow-circle-right fa-2x" aria-hidden="true"></i>'.html_safe, change_task_path(task, state: "done"), method: :put %>
            <% elsif task.state == "done" %>
                <li><%= link_to '<i class="fa fa-arrow-circle-left fa-2x" aria-hidden="true"></i>'.html_safe, change_task_path(task, state: "doing"), method: :put %></li>
            <% elsif task.state == "to_do" %>
                <li><%= link_to '<i class="fa fa-arrow-circle-right fa-2x" aria-hidden="true"></i>'.html_safe, change_task_path(task, state: "doing"), method: :put %></li>
            <% end %>
        
            </ul>    
        </div>
    </div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4">
    <h1 class="text-center"><label class="tituloTask"><i class="fa fa-pause-circle" aria-hidden="true"></i> To do</label></h1>
    <%= render @to_do%>
  </div>
  
  <div class="col-md-4">
    <h1 class="text-center"><label class="tituloTask"><i class="fa fa-clock-o" aria-hidden="true"></i> Doing</label></h1>
    <%= render @doing%>
  </div>
  
  <div class="col-md-4">
    <h1 class="text-center"><label class="tituloTask"><i class="fa fa-check-circle" aria-hidden="true"></i> Done</label></h1>
    <%= render @done%>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="panel panel-info">
        
        <div class="panel-heading">Created <%= time_ago_in_words(@task.created_at) %> </div>
        
        <div class="panel-body">
        
        <ul class="list-group">
        
        <li class="list-group-item active">Content: <%= @task.content %></li>
        <li class="list-group-item">State: <%= @task.state %></li>
        <li class="list-group-item"><i class="fa fa-pencil-square" aria-hidden="true"></i> <%= link_to 'Edit', edit_task_path(@task) %></li>
        <li class="list-group-item"><i class="fa fa-trash-o" aria-hidden="true"></i> <%= link_to 'Destroy', @task, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
        
        </div>
        
        <div class="panel-footer text-center">
          
          <% if @task.state == "doing" %>
                <%= link_to '<i class="fa fa-pause-circle fa-2x" aria-hidden="true"></i>'.html_safe, change_task_path(@task, state: "to_do"), method: :put, :title => "Change state to do" %>
                <%= link_to '<i class="fa fa-check-circle fa-2x" aria-hidden="true"></i>'.html_safe, change_task_path(@task, state: "done"), method: :put, :title => "Change state to done" %>
            <% else %>
                <li><%= link_to '<i class="fa fa-clock-o fa-2x" aria-hidden="true"></i>'.html_safe, change_task_path(@task, state: "doing"), method: :put, :title => "Change state to doing" %></li>
            <% end %>
            
        </div>
        
  </div>